### ISSUE TITLE
[Feature request] Scores and TOP10

### ISSUE THREAD

**Issue by ptkdev** [ptkdev/quizquickanswer-telegram-game-bot#2]
1 correct answer = 10 points

`/scores @your_name` show users score from databases/scores.json

`/top10` show top 10 of users from group:
1. username - 100 scores
2. username - 80 scores
3. username - 50 scores
4. username - 10 scores

Example scores.json

```json
{
  "scores": [
    {
      "id": 0,
      "is_bot": false,
      "first_name": "",
      "username": "",
      "language_code": "",
      "score": "10",
      "group_id": -000000000
    }
  ]
}
```

Extra parameters `score` and other from `ctx.update.message.from`

**Comment by AliShadman95** [comment]
Available in v0.3.0
