### ISSUE TITLE
[Bug Report] Master can answer it's own question

### ISSUE THREAD

**Issue by ImAl3x03** [ptkdev/quizquickanswer-telegram-game-bot#23]
### Versions

-   **App Version:** v0.7.7

### Expected Behavior

If master give's the correct answer, the bot shouldn't take it as valid

### Actual Behavior

The bot says the current muster is the winner of is own question

### Steps to Reproduce

Give the master yourself, create a question and give the right answer
![image](https://user-images.githubusercontent.com/66570558/218772177-2fcb4c11-3a61-4c4f-acb5-6065634317e2.png)

**Comment by giobar99** [comment]
This issue is fixed. You should close it.
